config/routes.rb
Rails.application.routes.draw do


  #configured for users, and sendgrid hello email through devise registartions
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  get 'home/index'

  resources :listings
  
  resources :conversations do
    resources :messages
   end

  root to: "listings#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  attr_accessor :photo
  mount_uploader :photo, PhotosForListingsUploader
  mount_uploader :photo2, PhotosForListingsUploader
  mount_uploader :photo3, PhotosForListingsUploader
  mount_uploader :photo4, PhotosForListingsUploader
  mount_uploader :photo5, PhotosForListingsUploader
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  #Configure for petergates roles "access all"
  access all: [:show, :index, :new, :edit, :create, :update, ], user: {except: [:destroy, ]}, message: "You shall not pass", admin: :all


  # params.require(:listing).permit({photo: []})
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:photo, :photo2, :photo3, :photo4, :photo5, :address, :property_type, :number_of_bedrooms, :number_of_bathrooms, :max_price_per_week, :available_date, :roles)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo%>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :listing_Address %>
  </div>

  <div class="field">
    <%= form.label :property_type %>
    <%= form.check_box  :property_type, id: :listing_property_type %>
  </div>

  <div class="field">
    <%= form.label :number_of_bedrooms %>
    <%= form.number_field :number_of_bedrooms, id: :listing_number_of_bedrooms %>
  </div>

  <div class="field">
    <%= form.label :number_of_bathrooms %>
    <%= form.number_field :number_of_bathrooms, id: :listing_number_of_bathrooms %>
  </div>

  <div class="field">
    <%= form.label :max_price_per_week %>
    <%= form.number_field :max_price_per_week, id: :listing_max_price_per_week %>
  </div>

  <div class="field">
    <%= form.label :available_date %>
    <%= form.number_field :available_date, id: :listing_available_date %>
  </div>

  <div class="field">
    <%= form.label :roles %>
    <%= form.number_field :roles, id: :listing_Roles %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Listings</h1>


  <head>
    <div class="responsive-table highlight">

    </div>
  </head>

  <body>
    <!-- materialize carousel pulling from cloudinary -->
    <% @listings.each do |listing| %>
      <div class="carousel carousel-slider">
        <a class="carousel-item" href="#one!"><img src="<%= listing.photo_url %>"></a>
        <a class="carousel-item" href="#two!"><img src="<%= listing.photo2_url %>"></a>
        <a class="carousel-item" href="#three!"><img src="<%= listing.photo3_url %>"></a>
        <a class="carousel-item" href="#four!"><img src="<%= listing.photo4_url %>"></a>
        <a class="carousel-item" href="#five!"><img src="<%= listing.photo5_url %>"></a>
      </div>
      <!-- referencing seed file and database -->
      <%= listing.rent_price_per_week %><img src="" alt="">
      <%= listing.number_of_bedrooms %>
      <%= listing.address %>
      <h1>😍</h1>



      <script type="text/javascript">
         $('.carousel.carousel-slider').carousel({fullWidth: true});
      </script>

    <% end %>
  </body>



<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <%= cl_image_tag(@listing.photo_url, :class => "uploaded_photo")  %>
</p>


<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>Property type:</strong>
  <%= @listing.property_type %>
</p>

<p>
  <strong>Number of bedrooms:</strong>
  <%= @listing.number_of_bedrooms %>
</p>

<p>
  <strong>Number of bathrooms:</strong>
  <%= @listing.number_of_bathrooms %>
</p>

<p>
  <strong>Max price per week:</strong>
  <%= @listing.max_price_per_week %>
</p>

<p>
  <strong>Available date:</strong>
  <%= @listing.available_date %>
</p>

<p>
  <strong>Roles:</strong>
  <%= @listing.roles %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>